version: '2'
services:
  websession:
    image: springsession:latest
    command: [--spring.redis.host=redis]
    links:
      - redis
  redis:
    image: redis:latest
    command: [redis-server]
  lb:
    image: dockercloud/haproxy:latest
    links:
      - websession
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80

