version: '2'
services:
  websession:
    image: springsession:latest
    command: [--spring.profiles.active=hazelcast]
  lb:
    image: dockercloud/haproxy:latest
    links:
      - websession
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80